#ifndef DRIVERS_FONT_H
#define DRIVERS_FONT_H

#include <stdint.h>

/* 8x16 bitmap font, one byte per row, msb = leftmost pixel.
 * data lives in font.c which is generated by tools/font2c.py */

#define FONT_WIDTH  8
#define FONT_HEIGHT 16

extern const uint8_t console_font[256][16];

#endif
